name: jotub_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  intl_utils: ^2.8.7

  #for theme_manager:
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_screenutil: ^5.9.0
  another_flushbar: ^1.12.30
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0

  #for flutter_state_management:
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  meta: ^1.10.0

  #for network_handler:
  connectivity_plus: any
  dartz: ^0.10.1
  dio: ^5.4.1
  retrofit: ^4.1.0

  #for data model_generator:
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  #for dependency_injection_flutter:
  get_it: ^7.6.7

  #for preferences_local_storage_inspector:
  shared_preferences: ^2.2.2

  #for firebase:
  firebase_core: any
  firebase_messaging: any
  fcm_config: any
  flutter_local_notifications: ^16.1.0

  #for flutter_keyboard_visibility:
  flutter_keyboard_visibility: ^6.0.0

  carousel_slider: ^4.2.1
  flip_card: ^0.7.0

  # cache image network
  cached_network_image: ^3.3.1

  # get image camera or gallery
  image_picker: ^1.0.4

  # scan qr code
  qr_code_scanner: ^1.0.1

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#043349"
  image: assets/images/image_splash_screen.png
  android: true
  ios: true
  android_gravity: fill_vertical
  ios_content_mode: scaleAspectFit

  android_12:
    image: assets/images/image_splash_screen.png
    icon_background_color: "#043349"
    android_gravity: fill_vertical

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app.jpg"
  min_sdk_android: 29

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  mocktail: ^1.0.3
  dartz_test: ^0.1.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/mini_game/
    - assets/images/
    - assets/images/order/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caster
      fonts:
        - asset: assets/fonts/Caster.otf
    - family: MyriadPro
      fonts:
        - asset: assets/fonts/MyriadPro-It.otf
          style: italic
        - asset: assets/fonts/MyriadPro-Bold.otf
          weight: 700
        - asset: assets/fonts/MyriadPro-Regular.otf
          style: normal
        - asset: assets/fonts/MyriadPro-Semibold.otf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf

flutter_intl:
  enabled: true
